# **TO - DO - Task**

## **4.1 Exercise on Functions:**

Task - 1:
Create a Python program that converts between different units of measurement.

• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.
• Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.
• Conversion Options:
1. Length:
– Convert meters (m) to feet (ft).
– Convert feet (ft) to meters (m).
2. Weight:
– Convert kilograms (kg) to pounds (lbs).
– Convert pounds (lbs) to kilograms (kg).
3. Volume:
– Convert liters (L) to gallons (gal).
– Convert gallons (gal) to liters (L).

In [ ]:
def meters_to_feet(meters):
    """
    Convert meters to feet.

    Parameters:
    meters (float): The length in meters.

    Returns:
    float: The length in feet.
    """
    return meters * 3.28084

def feet_to_meters(feet):
    return feet / 3.28084

def kilograms_to_pounds(kilograms):
    return kilograms * 2.20462

def pounds_to_kilograms(pounds):
    return pounds / 2.20462

def liters_to_gallons(liters):
    return liters * 0.264172

def gallons_to_liters(gallons):
    return gallons / 0.264172

def get_conversion_choice():
    print("Choose the type of conversion:")
    print("1. Length")
    print("2. Weight")
    print("3. Volume")
    choice = input("Enter your choice: ")
    return choice

def get_length_conversion_choice():
    print("Choose the length conversion:")
    print("1. Meters to Feet")
    print("2. Feet to Meters")
    choice = input("Enter your choice: ")
    return choice

def get_weight_conversion_choice():
    print("Choose the weight conversion:")
    print("1. Kilograms to Pounds")
    print("2. Pounds to Kilograms")
    choice = input("Enter your choice: ")
    return choice

def get_volume_conversion_choice():
    print("Choose the volume conversion:")
    print("1. Liters to Gallons")
    print("2. Gallons to Liters")
    choice = input("Enter your choice: ")
    return choice

def main():
    try:
        conversion_type = get_conversion_choice()

        if conversion_type == '1':
            length_choice = get_length_conversion_choice()
            value = float(input("Enter the length value to be converted: "))
            if length_choice == '1':
                result = meters_to_feet(value)
                print(f"{value} meters is equal to {result:.2f} feet.")
            elif length_choice == '2':
                result = feet_to_meters(value)
                print(f"{value} feet is equal to {result:.2f} meters.")
            else:
                print("Invalid length conversion choice.")

        elif conversion_type == '2':
            weight_choice = get_weight_conversion_choice()
            value = float(input("Enter the weight value to be converted: "))
            if weight_choice == '1':
                result = kilograms_to_pounds(value)
                print(f"{value} kilograms is equal to {result:.2f} pounds.")
            elif weight_choice == '2':
                result = pounds_to_kilograms(value)
                print(f"{value} pounds is equal to {result:.2f} kilograms.")
            else:
                print("Invalid weight conversion choice.")

        elif conversion_type == '3':
            volume_choice = get_volume_conversion_choice()
            value = float(input("Enter the volume value to be converted: "))
            if volume_choice == '1':
                result = liters_to_gallons(value)
                print(f"{value} liters is equal to {result:.2f} gallons.")
            elif volume_choice == '2':
                result = gallons_to_liters(value)
                print(f"{value} gallons is equal to {result:.2f} liters.")
            else:
                print("Invalid volume conversion choice.")

        else:
            print("Invalid conversion type choice.")

    except ValueError:
        print("Invalid input. Please enter a numeric value.")

if __name__ == "__main__":
    main()

Choose the type of conversion:
1. Length
2. Weight
3. Volume
Enter your choice: 2
Choose the weight conversion:
1. Kilograms to Pounds
2. Pounds to Kilograms
Enter your choice: 1
Enter the weight value to be converted: 1
1.0 kilograms is equal to 2.20 pounds.


Task - 2:
Create a Python program that performs various mathematical operations on a list of numbers.
• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).


3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.
• Requirements:

1. Functions: Define at least one function for each operation (sum, average, maximum, mini-
mum).

2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.

In [ ]:
def calculate_sum(numbers):
    """
    Calculate the sum of a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The sum of the numbers.
    """
    return sum(numbers)

def calculate_average(numbers):
    return sum(numbers) / len(numbers)

def find_maximum(numbers):
    return max(numbers)

def find_minimum(numbers):
    return min(numbers)

def get_numbers_from_user():
    input_string = input("Enter numbers separated by spaces: ")
    number_strings = input_string.split()
    numbers = [float(num) for num in number_strings]
    return numbers

def main():
    try:
        print("Choose an operation:")
        print("1. Sum")
        print("2. Average")
        print("3. Maximum")
        print("4. Minimum")
        choice = input("Enter the number corresponding to your choice: ")

        numbers = get_numbers_from_user()
        if not numbers:
            raise ValueError("The list of numbers is empty.")

        if choice == '1':
            result = calculate_sum(numbers)
            print(f"The sum of the numbers is: {result}")
        elif choice == '2':
            result = calculate_average(numbers)
            print(f"The average of the numbers is: {result}")
        elif choice == '3':
            result = find_maximum(numbers)
            print(f"The maximum value is: {result}")
        elif choice == '4':
            result = find_minimum(numbers)
            print(f"The minimum value is: {result}")
        else:
            print("Invalid choice. Please select a valid operation.")

    except ValueError as e:
        print(f"Invalid input: {e}")
    except ZeroDivisionError:
        print("Cannot calculate the average of an empty list.")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

if __name__ == "__main__":
    main()

Choose an operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter the number corresponding to your choice: 2
Enter numbers separated by spaces: 2 5 3
The average of the numbers is: 3.3333333333333335


# **4.2 Exercise on List Manipulation:**

In [ ]:
def extract_every_other(lst):
    """Return a new list containing every other element from the original list."""
    return lst[::2]

def get_sublist(lst, start, end):
    """Return a sublist from the original list, from index 'start' to 'end' inclusive."""
    return lst[start:end+1]

def reverse_list(lst):
    """Return a new list that is the reverse of the original list."""
    return lst[::-1]

def remove_first_last(lst):
    """Return a new list with the first and last elements removed from the original list."""
    return lst[1:-1]

def get_first_n(lst, n):
    """Return a new list containing the first 'n' elements of the original list."""
    return lst[:n]

def get_last_n(lst, n):
    """Return a new list containing the last 'n' elements of the original list."""
    return lst[-n:]

def reverse_skip(lst):
    """Return a new list containing every second element from the original list, starting from the second-to-last, moving backward."""
    return lst[-2::-2]

def main():
    options = {
        '1': ('Extract every other element', extract_every_other),
        '2': ('Slice a sublist', get_sublist),
        '3': ('Reverse the list', reverse_list),
        '4': ('Remove the first and last elements', remove_first_last),
        '5': ('Get the first n elements', get_first_n),
        '6': ('Get the last n elements', get_last_n),
        '7': ('Extract elements in reverse order skipping one', reverse_skip)
    }

    while True:
        print("\nChoose a list manipulation operation:")
        for key, (description, _) in options.items():
            print(f"{key}. {description}")
        print("8. Exit")

        choice = input("Enter the number of your choice: ")

        if choice == '8':
            print("Exiting the program.")
            break

        if choice not in options:
            print("Invalid choice. Please try again.")
            continue

        try:
            lst = input("Enter a list of elements separated by spaces: ").split()
            lst = [int(x) if x.isdigit() else x for x in lst]  # Convert numeric strings to integers

            if choice in ['2', '5', '6']:
                if choice == '2':
                    start = int(input("Enter the starting index: "))
                    end = int(input("Enter the ending index: "))
                    result = options[choice][1](lst, start, end)
                else:
                    n = int(input("Enter the number of elements (n): "))
                    result = options[choice][1](lst, n)
            else:
                result = options[choice][1](lst)

            print(f"Result: {result}")

        except ValueError as e:
            print(f"Invalid input: {e}")
        except IndexError as e:
            print(f"Index error: {e}")
        except Exception as e:
            print(f"An unexpected error occurred: {e}")

if __name__ == "__main__":
    main()


Choose a list manipulation operation:
1. Extract every other element
2. Slice a sublist
3. Reverse the list
4. Remove the first and last elements
5. Get the first n elements
6. Get the last n elements
7. Extract elements in reverse order skipping one
8. Exit
Enter the number of your choice: 5
Enter a list of elements separated by spaces: 1 3 5 7 9 11
Enter the number of elements (n): 4
Result: [1, 3, 5, 7]

Choose a list manipulation operation:
1. Extract every other element
2. Slice a sublist
3. Reverse the list
4. Remove the first and last elements
5. Get the first n elements
6. Get the last n elements
7. Extract elements in reverse order skipping one
8. Exit
Enter the number of your choice: 7
Enter a list of elements separated by spaces: 1 2 1 3 4 2 6 8
Result: [6, 4, 1, 1]

Choose a list manipulation operation:
1. Extract every other element
2. Slice a sublist
3. Reverse the list
4. Remove the first and last elements
5. Get the first n elements
6. Get the last n elements
7. Extrac

# **4.3 Exercise on Nested List:**

In [ ]:
def flatten(lst):
    """Flattens a nested list into a single-dimensional list."""
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(flatten(item))
        else:
            flat_list.append(item)
    return flat_list

def access_nested_element(lst, indices):
    """Accesses a specific element in a nested list given a list of indices."""
    element = lst
    for index in indices:
        element = element[index]
    return element

def sum_nested(lst):
    """Calculates the sum of all numbers in a nested list, regardless of depth."""
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

def remove_element(lst, elem):
    """Removes all occurrences of a specific element from a nested list."""
    if isinstance(lst, list):
        return [remove_element(item, elem) for item in lst if item != elem]
    else:
        return lst

def find_max(lst):
    """Finds the maximum element in a nested list, regardless of depth."""
    max_elem = float('-inf')
    for item in lst:
        if isinstance(item, list):
            max_elem = max(max_elem, find_max(item))
        else:
            max_elem = max(max_elem, item)
    return max_elem

def count_occurrences(lst, elem):
    """Counts how many times a specific element appears in a nested list."""
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

def deep_flatten(lst):
    """Flattens a list of lists of lists into a single list, regardless of depth."""
    return flatten(lst)

def average_nested(lst):
    """Calculates the average of all elements in a nested list."""
    flat_list = flatten(lst)
    return sum(flat_list) / len(flat_list) if flat_list else 0

if __name__ == "__main__":
    nested_list = [[1, 2], [3, [4, 5]], 6]
    print("Flattened list:", flatten(nested_list))
    print("Accessed element [1, 1]:", access_nested_element(nested_list, [1, 1]))
    print("Sum of elements:", sum_nested(nested_list))
    print("List after removing 2:", remove_element(nested_list, 2))
    print("Maximum element:", find_max(nested_list))
    print("Occurrences of 2:", count_occurrences(nested_list, 2))
    print("Deep flattened list:", deep_flatten(nested_list))
    print("Average of elements:", average_nested(nested_list))

Flattened list: [1, 2, 3, 4, 5, 6]
Accessed element [1, 1]: [4, 5]
Sum of elements: 21
List after removing 2: [[1], [3, [4, 5]], 6]
Maximum element: 6
Occurrences of 2: 1
Deep flattened list: [1, 2, 3, 4, 5, 6]
Average of elements: 3.5


# **To - Do - NumPy**

# **10.1 Basic Vector and Matrix Operation with Numpy.**

Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np

# 1. Initialize an empty array with size 2x2.
empty_array = np.empty((2, 2))
print("1. Empty array (2x2):\n", empty_array)

# 2. Initialize an all-ones array with size 4x2.
ones_array = np.ones((4, 2))
print("\n2. All-ones array (4x2):\n", ones_array)

# 3. Return a new array of given shape and type, filled with a fill value.
fill_value = 7
shape = (3, 3)
filled_array = np.full(shape, fill_value)
print("\n3. Array filled with", fill_value, "(3x3):\n", filled_array)

# 4. Return a new array of zeros with the same shape and type as a given array.
given_array = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_array = np.zeros_like(given_array)
print("\n4. Array of zeros with the same shape as given array:\n", zeros_like_array)

# 5. Return a new array of ones with the same shape and type as a given array.
ones_like_array = np.ones_like(given_array)
print("\n5. Array of ones with the same shape as given array:\n", ones_like_array)

# 6. Convert an existing list to a NumPy array.
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\n6. NumPy array converted from list:\n", numpy_array)


1. Empty array (2x2):
 [[1.92584185e-316 0.00000000e+000]
 [1.58101007e-322 6.65545295e-310]]

2. All-ones array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Array filled with 7 (3x3):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Array of zeros with the same shape as given array:
 [[0 0 0]
 [0 0 0]]

5. Array of ones with the same shape as given array:
 [[1 1 1]
 [1 1 1]]

6. NumPy array converted from list:
 [1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
# 1. Create an array with values ranging from 10 to 49.
array_10_to_49 = np.arange(10, 50)
print("1. Array with values from 10 to 49:\n", array_10_to_49)

# 2. Create a 3x3 matrix with values ranging from 0 to 8.
matrix_0_to_8 = np.arange(9).reshape(3, 3)
print("\n2. 3x3 matrix with values from 0 to 8:\n", matrix_0_to_8)

# 3. Create a 3x3 identity matrix.
identity_matrix = np.eye(3)
print("\n3. 3x3 identity matrix:\n", identity_matrix)

# 4. Create a random array of size 30 and find the mean of the array.
random_array_30 = np.random.random(30)
mean_random_array_30 = random_array_30.mean()
print("\n4. Mean of random array of size 30:\n", mean_random_array_30)

# 5. Create a 10x10 array with random values and find the minimum and maximum values.
random_matrix_10x10 = np.random.random((10, 10))
min_value = random_matrix_10x10.min()
max_value = random_matrix_10x10.max()
print("\n5. Minimum and maximum values in 10x10 random matrix:\n", min_value, max_value)

# 6. Create a zero array of size 10 and replace the 5th element with 1.
zero_array_10 = np.zeros(10)
zero_array_10[4] = 1  # Index 4 corresponds to the 5th element
print("\n6. Zero array of size 10 with 5th element as 1:\n", zero_array_10)

# 7. Reverse an array arr = [1, 2, 0, 0, 4, 0].
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\n7. Reversed array [1, 2, 0, 0, 4, 0]:\n", reversed_arr)

# 8. Create a 2D array with 1 on the border and 0 inside.
bordered_array = np.ones((5, 5))
bordered_array[1:-1, 1:-1] = 0
print("\n8. 2D array with 1 on the border and 0 inside:\n", bordered_array)

# 9. Create an 8x8 matrix and fill it with a checkerboard pattern.
checkerboard_matrix = np.zeros((8, 8))
checkerboard_matrix[1::2, ::2] = 1
checkerboard_matrix[::2, 1::2] = 1
print("\n9. 8x8 checkerboard pattern:\n", checkerboard_matrix)

1. Array with values from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 matrix with values from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3x3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Mean of random array of size 30:
 0.5141497089641277

5. Minimum and maximum values in 10x10 random matrix:
 0.0010052077787333635 0.9902474955005185

6. Zero array of size 10 with 5th element as 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

7. Reversed array [1, 2, 0, 0, 4, 0]:
 [0 4 0 0 2 1]

8. 2D array with 1 on the border and 0 inside:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

9. 8x8 checkerboard pattern:
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

addition = x + y
print("Addition of x and y:")
print(addition)

subtraction = x - y
print("Subtraction of y from x:")
print(subtraction)

multiplied = x * 3
print("x multiplied by 3:")
print(multiplied)

x_squared = x ** 2
print("Square of each element in x:")
print(x_squared)

# Dot product of v and w
dot_v_w = np.dot(v, w)
print("Dot product of v and w:", dot_v_w)

# Dot product of x and v
dot_x_v = np.dot(x, v)
print("Dot product of x and v:", dot_x_v)

# Dot product of x and y
dot_x_y = np.dot(x, y)
print("Dot product of x and y:")
print(dot_x_y)

# Concatenate x and y along rows (axis=0)
concat_row = np.concatenate((x, y), axis=0)
print("Concatenate x and y along rows:")
print(concat_row)

# Alternative using vstack
vstack_result = np.vstack((x, y))
print("\nUsing vstack for x and y:")
print(vstack_result)

# Reshape v and w to column vectors and concatenate along columns
v_col = v.reshape(-1, 1)
w_col = w.reshape(-1, 1)
concat_col = np.concatenate((v_col, w_col), axis=1)
print("\nConcatenate v and w as columns:")
print(concat_col)

try:
    concat_x_v = np.concatenate((x, v), axis=0)
    print("Concatenate x and v:")
    print(concat_x_v)
except ValueError as e:
    print("Error:", e)
    print("\nExplanation: The error occurs because x and v have different shapes.")
    print("x has shape", x.shape, "and v has shape", v.shape)
    print("To concatenate arrays, their dimensions must match except along the axis of concatenation.")

    # To fix this, we can reshape v
    v_reshaped = v.reshape(1, 2)
    concat_x_v_fixed = np.concatenate((x, v_reshaped), axis=0)
    print("\nAfter reshaping v to", v_reshaped.shape, "we can concatenate:")
    print(concat_x_v_fixed)

Addition of x and y:
[[ 6  8]
 [10 13]]
Subtraction of y from x:
[[-4 -4]
 [-4 -3]]
x multiplied by 3:
[[ 3  6]
 [ 9 15]]
Square of each element in x:
[[ 1  4]
 [ 9 25]]
Dot product of v and w: 219
Dot product of x and v: [29 77]
Dot product of x and y:
[[19 22]
 [50 58]]
Concatenate x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Using vstack for x and y:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v and w as columns:
[[ 9 11]
 [10 12]]
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Explanation: The error occurs because x and v have different shapes.
x has shape (2, 2) and v has shape (2,)
To concatenate arrays, their dimensions must match except along the axis of concatenation.

After reshaping v to (1, 2) we can concatenate:
[[ 1  2]
 [ 3  5]
 [ 9 10]]


Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

In [ ]:
import numpy as np

# Problem 4: Matrix Operations
print("Problem 4: Matrix Operations")

# Defining matrices A and B
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

print("Matrix A:\n", A)
print("Matrix B:\n", B)

# 1. Prove A.A^(-1) = I
print("\n1. Proving A.A^(-1) = I")
A_inv = np.linalg.inv(A)
print("A^(-1):\n", A_inv)
print("A.A^(-1):\n", np.dot(A, A_inv))
print("This is approximately the identity matrix I (small differences due to floating-point precision)")

# 2. Prove AB ≠ BA
print("\n2. Proving AB ≠ BA")
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB:\n", AB)
print("BA:\n", BA)
print("AB = BA:", np.array_equal(AB, BA))
print("Therefore, AB ≠ BA is proven")

# 3. Prove (AB)^T = B^T.A^T
print("\n3. Proving (AB)^T = B^T.A^T")
AB_transpose = np.transpose(np.dot(A, B))
print("(AB)^T:\n", AB_transpose)

B_transpose = np.transpose(B)
A_transpose = np.transpose(A)
BT_AT = np.dot(B_transpose, A_transpose)
print("B^T.A^T:\n", BT_AT)
print("(AB)^T = B^T.A^T:", np.array_equal(AB_transpose, BT_AT))
print("Therefore, (AB)^T = B^T.A^T is proven")

# Solving the system of linear equations
print("\n------ Solving the system of linear equations ------")
print("2x - 3y + z = -1")
print("x - y + 2z = -3")
print("3x + y - z = 9")

# Setting up the coefficient matrix A and constants vector B
coefficients = np.array([
    [2, -3, 1],
    [1, -1, 2],
    [3, 1, -1]
])

constants = np.array([-1, -3, 9])

print("\nMatrix form: AX = B")
print("Coefficient matrix A:\n", coefficients)
print("Constants vector B:", constants)

# Solving using inverse method manually
print("\nSolving using inverse method manually:")
coef_inv = np.linalg.inv(coefficients)
print("A^(-1):\n", coef_inv)
solution_manual = np.dot(coef_inv, constants)
print("Solution X = A^(-1)B:", solution_manual)

# Solving using np.linalg.solve function
print("\nSolving using np.linalg.solve function:")
solution_solve = np.linalg.solve(coefficients, constants)
print("Solution X:", solution_solve)

# Verifying the solution
print("\nVerifying the solution:")
print("AX =", np.dot(coefficients, solution_solve))
print("This should match B:", constants)

Problem 4: Matrix Operations
Matrix A:
 [[3 4]
 [7 8]]
Matrix B:
 [[5 3]
 [2 1]]

1. Proving A.A^(-1) = I
A^(-1):
 [[-2.    1.  ]
 [ 1.75 -0.75]]
A.A^(-1):
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
This is approximately the identity matrix I (small differences due to floating-point precision)

2. Proving AB ≠ BA
AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
AB = BA: False
Therefore, AB ≠ BA is proven

3. Proving (AB)^T = B^T.A^T
(AB)^T:
 [[23 51]
 [13 29]]
B^T.A^T:
 [[23 51]
 [13 29]]
(AB)^T = B^T.A^T: True
Therefore, (AB)^T = B^T.A^T is proven

------ Solving the system of linear equations ------
2x - 3y + z = -1
x - y + 2z = -3
3x + y - z = 9

Matrix form: AX = B
Coefficient matrix A:
 [[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]
Constants vector B: [-1 -3  9]

Solving using inverse method manually:
A^(-1):
 [[ 0.05263158  0.10526316  0.26315789]
 [-0.36842105  0.26315789  0.15789474]
 [-0.21052632  0.57894737 -0.05263158]]
Solution X = A^(-1)B: [ 2.  1. -2.]

Sol

10.2 Experiment: How Fast is Numpy?
In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:
1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.
2. Element-wise Multiplication
• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.
Measure and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.
3. Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.
4. Matrix Multiplication

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation.

In [ ]:
import numpy as np
import time
import random

print("Speed Comparison: Python Lists vs NumPy Arrays")
print("="*50)

# Function to measure execution time
def time_execution(func, *args):
    start_time = time.time()
    result = func(*args)
    end_time = time.time()
    return result, end_time - start_time

# 1. Element-wise Addition
print("\n1. Element-wise Addition (size: 1,000,000)")
print("-"*50)

# Create lists and arrays of size 1,000,000
size = 1000000
list1 = [random.random() for _ in range(size)]
list2 = [random.random() for _ in range(size)]
array1 = np.array(list1)
array2 = np.array(list2)

# Python list element-wise addition
def list_addition(l1, l2):
    return [a + b for a, b in zip(l1, l2)]

_, list_add_time = time_execution(list_addition, list1, list2)
print(f"Python List Addition Time: {list_add_time:.6f} seconds")

# NumPy array element-wise addition
_, numpy_add_time = time_execution(np.add, array1, array2)
print(f"NumPy Array Addition Time: {numpy_add_time:.6f} seconds")
print(f"NumPy is {list_add_time/numpy_add_time:.2f}x faster")

# 2. Element-wise Multiplication
print("\n2. Element-wise Multiplication (size: 1,000,000)")
print("-"*50)

# Python list element-wise multiplication
def list_multiplication(l1, l2):
    return [a * b for a, b in zip(l1, l2)]

_, list_mul_time = time_execution(list_multiplication, list1, list2)
print(f"Python List Multiplication Time: {list_mul_time:.6f} seconds")

# NumPy array element-wise multiplication
_, numpy_mul_time = time_execution(np.multiply, array1, array2)
print(f"NumPy Array Multiplication Time: {numpy_mul_time:.6f} seconds")
print(f"NumPy is {list_mul_time/numpy_mul_time:.2f}x faster")

# 3. Dot Product
print("\n3. Dot Product (size: 1,000,000)")
print("-"*50)

# Python list dot product
def list_dot_product(l1, l2):
    return sum(a * b for a, b in zip(l1, l2))

_, list_dot_time = time_execution(list_dot_product, list1, list2)
print(f"Python List Dot Product Time: {list_dot_time:.6f} seconds")

# NumPy array dot product
_, numpy_dot_time = time_execution(np.dot, array1, array2)
print(f"NumPy Array Dot Product Time: {numpy_dot_time:.6f} seconds")
print(f"NumPy is {list_dot_time/numpy_dot_time:.2f}x faster")

# 4. Matrix Multiplication
print("\n4. Matrix Multiplication (size: 1000x1000)")
print("-"*50)

# Creating smaller matrices for practical reasons
matrix_size = 100  # Using 100x100 instead of 1000x1000 to make it run in reasonable time
print(f"Note: Using {matrix_size}x{matrix_size} matrices instead of 1000x1000 for practical demonstration")

# Create Python lists as matrices
list_matrix1 = [[random.random() for _ in range(matrix_size)] for _ in range(matrix_size)]
list_matrix2 = [[random.random() for _ in range(matrix_size)] for _ in range(matrix_size)]

# Create NumPy array matrices
numpy_matrix1 = np.array(list_matrix1)
numpy_matrix2 = np.array(list_matrix2)

# Python list matrix multiplication
def list_matrix_multiply(m1, m2):
    result = [[0 for _ in range(len(m2[0]))] for _ in range(len(m1))]
    for i in range(len(m1)):
        for j in range(len(m2[0])):
            for k in range(len(m2)):
                result[i][j] += m1[i][k] * m2[k][j]
    return result

_, list_matmul_time = time_execution(list_matrix_multiply, list_matrix1, list_matrix2)
print(f"Python List Matrix Multiplication Time: {list_matmul_time:.6f} seconds")

# NumPy array matrix multiplication
_, numpy_matmul_time = time_execution(np.matmul, numpy_matrix1, numpy_matrix2)
print(f"NumPy Array Matrix Multiplication Time: {numpy_matmul_time:.6f} seconds")
print(f"NumPy is {list_matmul_time/numpy_matmul_time:.2f}x faster")

# Summary
print("\nSUMMARY")
print("="*50)
print(f"Element-wise Addition: NumPy is {list_add_time/numpy_add_time:.2f}x faster")
print(f"Element-wise Multiplication: NumPy is {list_mul_time/numpy_mul_time:.2f}x faster")
print(f"Dot Product: NumPy is {list_dot_time/numpy_dot_time:.2f}x faster")
print(f"Matrix Multiplication: NumPy is {list_matmul_time/numpy_matmul_time:.2f}x faster")
print("\nNote: The exact speed ratios may vary based on your hardware and system load.")
print("="*50)

Speed Comparison: Python Lists vs NumPy Arrays

1. Element-wise Addition (size: 1,000,000)
--------------------------------------------------
Python List Addition Time: 0.121179 seconds
NumPy Array Addition Time: 0.006059 seconds
NumPy is 20.00x faster

2. Element-wise Multiplication (size: 1,000,000)
--------------------------------------------------
Python List Multiplication Time: 0.105809 seconds
NumPy Array Multiplication Time: 0.006286 seconds
NumPy is 16.83x faster

3. Dot Product (size: 1,000,000)
--------------------------------------------------
Python List Dot Product Time: 0.117916 seconds
NumPy Array Dot Product Time: 0.001579 seconds
NumPy is 74.69x faster

4. Matrix Multiplication (size: 1000x1000)
--------------------------------------------------
Note: Using 100x100 matrices instead of 1000x1000 for practical demonstration
Python List Matrix Multiplication Time: 0.155036 seconds
NumPy Array Matrix Multiplication Time: 0.000307 seconds
NumPy is 504.87x faster

SUMMARY
E